language: c

os:
  - linux
  - osx
  
env:
 - CABALVER=1.22 GHCVER=7.10.2
 
install:
    - echo $TRAVIS_OS_NAME
    
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo add-apt-repository -y ppa:hvr/ghc; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry cabal update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cabal install idris --only-dependencies; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait cabal install idris; fi
         
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install idris; fi
    
    - git clone https://github.com/edwinb/SDL-idris
    - cd SDL-idris
    - idris --install sdl.ipkg
    - cd ..
      
script:
    - idris --build conway.ipkg
